// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title ZaoSettlement
 * @notice Handles secure on-chain payouts for Zao Poker using EIP-712 signatures.
 * Players can submit claims signed by the ZAO authority to claim their winnings.
 */
contract ZaoSettlement is EIP712, Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // The address of the ZAO off-chain authority that signs the claims
    address public zaoAuthority;

    // Mapping to track used nonces for each claimant to prevent replay attacks
    mapping(address => mapping(uint256 => bool)) public usedNonces;

    // Claim struct matching the EIP-712 typed data structure
    struct PayoutClaim {
        address recipient;
        address token;
        uint256 amount;
        uint256 nonce;
        uint256 deadline;
    }

    // Typehash for EIP-712
    bytes32 public constant CLAIM_TYPEHASH = keccak256(
        "PayoutClaim(address recipient,address token,uint256 amount,uint256 nonce,uint256 deadline)"
    );

    // Events
    event Claimed(
        address indexed recipient,
        address indexed token,
        uint256 amount,
        uint256 nonce
    );
    event ZaoAuthorityUpdated(address indexed oldAuthority, address indexed newAuthority);
    event DepositReceived(address indexed sender, address indexed token, uint256 amount);
    event EmergencyWithdrawn(address indexed token, address indexed recipient, uint256 amount);

    /**
     * @dev Constructor to initialize the contract.
     * @param _zaoAuthority The address of the off-chain authority signing the payout claims.
     */
    constructor(address _zaoAuthority) 
        EIP712("ZaoSettlement", "1") 
        Ownable(msg.sender)
    {
        require(_zaoAuthority != address(0), "Invalid ZAO authority address");
        zaoAuthority = _zaoAuthority;
        emit ZaoAuthorityUpdated(address(0), _zaoAuthority);
    }

    /**
     * @dev Claims the winnings using an EIP-712 signature from the ZAO authority.
     * @param recipient The address of the player receiving the funds.
     * @param token The ERC20 token address, or address(0) for native ETH.
     * @param amount The amount of tokens or ETH to claim.
     * @param nonce The unique nonce for this claim.
     * @param deadline The timestamp after which the signature expires.
     * @param signature The EIP-712 signature from the ZAO authority.
     */
    function claim(
        address recipient,
        address token,
        uint256 amount,
        uint256 nonce,
        uint256 deadline,
        bytes calldata signature
    ) external nonReentrant {
        require(block.timestamp <= deadline, "Claim signature expired");
        require(!usedNonces[recipient][nonce], "Nonce already used");

        // Hash the struct data according to EIP-712
        bytes32 structHash = keccak256(
            abi.encode(
                CLAIM_TYPEHASH,
                recipient,
                token,
                amount,
                nonce,
                deadline
            )
        );

        // Compute the typed data hash to recover the signer
        bytes32 hash = _hashTypedDataV4(structHash);
        address signer = ECDSA.recover(hash, signature);

        // Verify the signature was generated by the ZAO authority
        require(signer == zaoAuthority, "Invalid ZAO signature");

        // Mark nonce as used before transferring to prevent reentrancy / replay
        usedNonces[recipient][nonce] = true;

        // Perform the transfer
        if (token == address(0)) {
            require(address(this).balance >= amount, "Insufficient ETH balance in contract");
            (bool success, ) = recipient.call{value: amount}("");
            require(success, "ETH transfer failed");
        } else {
            IERC20(token).safeTransfer(recipient, amount);
        }

        emit Claimed(recipient, token, amount, nonce);
    }

    /**
     * @dev Allows the owner to update the ZAO authority address.
     * @param _newAuthority The new ZAO authority address.
     */
    function setZaoAuthority(address _newAuthority) external onlyOwner {
        require(_newAuthority != address(0), "Invalid ZAO authority address");
        address oldAuthority = zaoAuthority;
        zaoAuthority = _newAuthority;
        emit ZaoAuthorityUpdated(oldAuthority, _newAuthority);
    }

    /**
     * @dev Allows anyone to fund the contract or deposit tokens manually.
     * @param token The ERC20 token address, or address(0) for native ETH.
     * @param amount The amount of tokens to deposit (ignored for ETH).
     */
    function deposit(address token, uint256 amount) external payable {
        if (token == address(0)) {
            require(msg.value > 0, "Must deposit some ETH");
            emit DepositReceived(msg.sender, address(0), msg.value);
        } else {
            require(amount > 0, "Must deposit some tokens");
            IERC20(token).safeTransferFrom(msg.sender, address(this), amount);
            emit DepositReceived(msg.sender, token, amount);
        }
    }

    /**
     * @dev Allows the owner to withdraw any funds from the contract in case of emergency.
     * @param token The ERC20 token address, or address(0) for native ETH.
     * @param amount The amount to withdraw.
     * @param to The recipient address.
     */
    function emergencyWithdraw(
        address token,
        uint256 amount,
        address to
    ) external onlyOwner {
        require(to != address(0), "Invalid recipient address");
        
        if (token == address(0)) {
            require(address(this).balance >= amount, "Insufficient ETH balance");
            (bool success, ) = to.call{value: amount}("");
            require(success, "ETH transfer failed");
        } else {
            IERC20(token).safeTransfer(to, amount);
        }
        
        emit EmergencyWithdrawn(token, to, amount);
    }

    // Required to receive native ETH when token address is address(0)
    receive() external payable {
        emit DepositReceived(msg.sender, address(0), msg.value);
    }
}
